# -*- coding: utf-8 -*-
"""딥러닝 이미지 구현.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1xyNVbOv3UEtcRWfythy8ZdJf1W12Cv
"""

!pip install googletrans==4.0.0-rc1

from diffusers import AutoPipelineForText2Image
import torch
import os
from PIL import Image
from googletrans import Translator  # Google Translator 라이브러리 사용

def translate_text(text, src="ko", dest="en"):
    """텍스트를 영어로 번역"""
    translator = Translator()
    translated = translator.translate(text, src=src, dest=dest)
    return translated.text

def enrich_prompt(text):
    """프롬프트를 보강하여 세부적으로 표현"""
    return f"{text}, highly detailed, vibrant colors, cinematic lighting, fantasy style"

def generate_images(prompt, num_images=5, steps=30, guidance=7.5, output_dir="generated_images"):
    """텍스트 기반 이미지 생성"""
    os.makedirs(output_dir, exist_ok=True)
    image_paths = []
    for i in range(num_images):
        try:
            output = pipe(prompt=prompt, num_inference_steps=steps, guidance_scale=guidance)
            image = output.images[0]
            image_path = os.path.join(output_dir, f"image_{i + 1}.png")
            image.save(image_path)
            image_paths.append(image_path)
        except Exception as e:
            print(f"이미지 생성 중 오류 발생: {e}")
    return image_paths

def select_images(image_paths):
    """사용자가 생성된 이미지 중 선택"""
    print("\n생성된 이미지 목록:")
    for i, path in enumerate(image_paths):
        print(f"{i + 1}: {path}")
    selected_indices = input("사용자가 선택한 이미지 번호를 쉼표로 구분하여 입력하세요 (예: 1,3): ").strip()
    selected_indices = [int(idx) - 1 for idx in selected_indices.split(",") if idx.isdigit()]
    return [image_paths[i] for i in selected_indices if 0 <= i < len(image_paths)]

# Stable Diffusion 모델 로드
pipe = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/stable-diffusion-2-1",
    torch_dtype=torch.float32
)

# 디바이스 설정 (GPU 또는 CPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
pipe.to(device)

# 사용자 입력 처리
dream_text = input("꿈 내용을 입력하세요 (한국어): ").strip()

if dream_text:
    print("\n### 번역 및 GAN 처리 시작 ###")
    translated_text = translate_text(dream_text)  # 한국어를 영어로 번역
    print(f"번역된 텍스트: {translated_text}")
    enriched_text = enrich_prompt(translated_text)  # 번역된 텍스트를 프롬프트로 보강
    generated_images = generate_images(enriched_text)
    selected_images = select_images(generated_images)
    print(f"선택된 이미지: {selected_images}")
else:
    print("입력된 텍스트가 없습니다.")